export const vector: string[][] = [["user", "people-circle", "user_entity", "first"], ["role", "calendar3", "role", "second"],["food", "toggles2", "food", "third"], ["food category", "table", "food_category", "fourth"], ["military", "chat-quote-fill", "military", "fifth"], ["composite_unit", "collection", "composite_unit", "sixth"],
["weather", "chm", "weather"],
    // ["weather12", "home", "weather12"],
    // ["t weatherOffShore", "home", "weatherOffShore"],
    // ["t weatherOnShore", "speedometer2", "weatherOnShore"],
    // ["t weatherHistoric", "bootstrap", "weatherHistoric"],
    // ["t weatherHistoricOffShore", "table", "weatherHistoricOffShore"],
    // ["t weatherHistoricOnShore", "geo-fill", "weatherHistoricOnShore"],
    // ["commission", "collection", "commission"],
    // ["country", "table", "country"],
    // ["equipment", "people-circle", "equipment"],
    // ["harbor", "grid", "harbor"],
    // ["institution", "collection", "institution"],
    // ["manufacturer", "collection", "manufacturer"],
    ["observer", "collection", "observer"],
    // ["om", "collection", "om"],
    ["platform", "calendar3", "platform"],
    // ["platform_category", "chat-quote-fill", "platform_category"],
    // ["researcher", "collection", "researcher"],
    // ["station", "cpu-fill", "station"],
    ["station_category", "gear-fill", "stationCategory"],
    // ["station_historic", "cpu-fill", "station_historic"],
    ["station_off_shore", "speedometer", "stationOffShore"],
    ["station_on_shore", "toggles2", "stationOnShore"],
    // ["surveying", "collection", "surveying"],
    ["tooltip user", "grid", "userEntity"],
    // ["tooltip role", "chevron-right", "role"],
    // ["tooltip profile", "people-circle", "profile"]
]